<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3FPT81S" failures="1" tests="1" name="VOIS_Automation_Challenge" time="7.171" errors="0" timestamp="29 Oct 2022 19:21:28 GMT">
  <testcase classname="TestClasses.SearchSizeTest" name="firstTest" time="4.711">
    <failure type="java.lang.AssertionError" message="expected [9] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [10]
at TestClasses.SearchSizeTest.firstTest(SearchSizeTest.java:52)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- firstTest -->
</testsuite> <!-- VOIS_Automation_Challenge -->
